/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        System.out.println("Respeite as leis de trânsito :D");
    }
}
